security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: default

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
