vich_uploader:
    db_driver: orm

    mappings:
        clients:
            uri_prefix: /uploads/clients
            upload_destination: '%kernel.project_dir%/public/uploads/clients'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: Vich\UploaderBundle\Naming\OrignameNamer
